# Generated by Django 2.2.13 on 2020-06-04 12:43

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_urgent', models.BooleanField(default=False)),
                ('recall_nums', models.PositiveSmallIntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0001_pending', '대기'), ('0010_in_progress', '진행중'), ('0100_transferred', '이관완료'), ('1000_completed', '완료'), ('1100_canceled', '취소됨')], max_length=30)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Issue')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='issues.Task')),
            ],
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['modified'], name='task_modified'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created'], name='task_created'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['modified'], name='issue_modified'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['created'], name='issue_created'),
        ),
    ]
